# Generated by Django 4.1 on 2024-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='detail',
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
    ]
