# Generated by Django 4.1 on 2024-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_remove_producto_detail_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detail',
            field=models.TextField(default='', verbose_name='detalle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen'),
        ),
    ]
